Upload version 1 best practices documentation
physiopy/physiopy-community-guidelines pull request #3
Opened 2024-02-12 20:22 UTC by beccaclements99

Version 1 of best practices documentation

## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [ ] `infrastructure` (no version update)
- [x] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [x] \[Documentation only\] I built the docs locally.
- [ ] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [ ] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [x] Please, comment on my PR while it's a draft and give me feedback on the development!

2024-02-28 15:00 UTC, RayStick commented on docs/source/physio_importance.md
> +Another benefit of collecting physiological data is that it provides a method to **monitor the subject and/or patient during the scan in real-time.** Any sudden changes in the different aspects being
```suggestion
Another benefit of collecting physiological data is that it provides a method to **monitor the subject and/or patient during the scan in real-time.** Any sudden changes in the different aspects being monitored can help those in the control room identify if the person is experiencing discomfort or complying with the scan protocol. Looking out for these changes is particularly helpful during an individual's first MRI scan, when they may react poorly to the scan environment. In some protocols, tracking physiology in real-time can ensure that values stay within safe limits, in accordance with what is approved by your Institutional Review Board (IRB) or Research Ethics Committee (REC). 
```

2024-02-28 15:00 UTC, RayStick commented on docs/source/physio_importance.md
> +Another benefit of collecting physiological data is that it provides a method to **monitor the subject and/or patient during the scan in real-time.** Any sudden changes in the different aspects being
IRB is a US specific term, so I made it more general

2024-02-28 15:28 UTC, RayStick commented on docs/source/process_phys.md
> +    * Cons:peak detection in these models may require manual effort, and efforts should be made to automate this process.
```suggestion
    * Cons: peak detection in these models may require manual effort, and efforts should be made to automate this process.
```

2024-02-28 16:22 UTC, likeajumprope reviewed
Fantastic effort, and very well written!

2024-02-28 16:22 UTC, likeajumprope commented on docs/source/physiopy_community.md
> +The most common types of physiological data acquired in fMRI analysis within members of our community are cardiac (photoplethysmographypulse, ECG/EKG) and respiration, either ventilation (respiratory
The first and second sentence somehow do not flow - what does the "their" in "their lab websites" refer to? Data? Maybe change "their" to "some common examples by labs of members in the community" or something

2024-02-28 16:22 UTC, likeajumprope commented on docs/source/physiopy_community.md
> +The most common types of physiological data acquired in fMRI analysis within members of our community are cardiac (photoplethysmographypulse, ECG/EKG) and respiration, either ventilation (respiratory
```suggestion
The most common types of physiological data acquired in fMRI analysis within members of our community are cardiac (photoplethysmographypulse, ECG/EKG) and respiration, either ventilation (respiratory belt) and/or gas concentration (particularly expired CO2). Links to some common examples and tools provided by members of the community and their labs' websites are listed below if you wish to reach out about questions or look through any methods/analyses in their publications.
```

2024-02-28 17:37 UTC, rgbayrak requested changes
Some references are incomplete, not added to the References list as a full citation and different formatting. 

Citations under data collection section that do not appear in References:

- (Liu et al., 2019)
- Bulte and Wartolowska (2017)
- Zvolanek et al., NeuroImage, 2023
- Liu et al., 2017
- Pinto et al. 2021

Also some in Data Processing section as well (disclaimer: I did not check every tab)
(Bhattacharyya and Lowe, 2004).


References Section/Tab: 
Not alphabetically ordered, making it hard to read, i.e. Bottenhorn comes last.

2024-02-28 20:16 UTC, me-pic reviewed
Great work ! 

I just added really minor comments, please feel free to ignore them if not relevant.

2024-02-29 11:48 UTC, m-miedema commented on docs/source/phys_set_up.md
+1 for the citation of the community practice meeting [SETUP_170322] being confusing.

2024-02-29 11:57 UTC, m-miedema commented on docs/source/collect_phys.md
Typo: For particularly thin subjects, adding a pad between the belt and the chest might be necessary to avoid saturation due to loose**n** belts.

2024-02-29 12:02 UTC, m-miedema commented
It's exciting the way this is coming together! My main comments are that 

1. The in-text references to community meetings, while helpful internally, are not helpful in this context. Perhaps there could be a list of topics that have been discussed and in-text references that make it more clear that we're referencing a conversation? E.g. (Community Practice Meeting: Respiration, date).
2. The comment regarding eddy currents should be moved out of the gas section and into a more general practice for collecting data.

2024-03-12 01:40 UTC, goodalse2019 commented
This all looks amazing! Awesome job everyone. Super excited for this to go public.

2024-03-12 14:51 UTC, joanacspinto commented
Hi all, I've taken a brief look at this - amazing work! Well done :)
Just some minor points: 
- the references to the community meetings look a bit odd
- the order. I would recommend moving "2. Community" to a later stage. I like the flow of 1. motivation, 2. setting up the system, 3. acquiring data, 3. analysing data etc

2024-03-20 06:36 UTC, afni-dglen commented
This is really nice work on this documentation, and I learned a lot reading this. I will note a few nit-picky details - please see the atttached md files. 

[collect_phys.md](https://github.com/physiopy/physiopy-community-guidelines/files/14662711/collect_phys.md)
[process_phys.md](https://github.com/physiopy/physiopy-community-guidelines/files/14662758/process_phys.md)
[physio_importance.md](https://github.com/physiopy/physiopy-community-guidelines/files/14662429/physio_importance.md)
[phys_set_up.md](https://github.com/physiopy/physiopy-community-guidelines/files/14662522/phys_set_up.md)

2024-03-21 15:15 UTC, isesteves commented on docs/source/phys_set_up.md
Thank you for spotting that @rgbayrak, I added those and more references that were missing (here 5083560). The Community Practices Meetings list was also added to the references. Maybe we can cite them like "(CPM1, March 2022)", @rgbayrak and @m-miedema?

2024-03-21 15:52 UTC, isesteves commented on docs/source/phys_set_up.md
The other comments have been addressed here 6383ff6 (except for the references to the Community Practices meetings, which will be fixed when we have a consensus on the nomenclature).

2024-03-25 19:43 UTC, patriciampfigueiredo commented on docs/source/physiopy_community.md
Typo? photoplethysmographypulse.

This section would probably make more sense after the types of signals have been introduced (in the next section?). Depending on which section comes first, you may want to introduce all acronyms the first time they appear (including ECG /EKG as well as PPG).

2024-03-25 19:50 UTC, patriciampfigueiredo commented on docs/source/physio_importance.md
I think "in real-time" should be "in real time" (since it is not an adjective here).

I would replace "introduction to what physiological data" with "introduction to which physiological signals".

I would replace "Physiological monitoring is a key component of the understanding of" with "Physiological monitoring is key to understanding".

There is a reference to Caballero-Gaudes 2006 twice in this section, but I feel others (from the list) would be appropriate too.

2024-03-25 19:54 UTC, patriciampfigueiredo commented on docs/source/process_phys.md
I don't think this is correct... "the peak detection step employed to compute the cardiac rate may be done using either the EEG (heart rate) or the ECG (pulse rate)".

To be removed from here? [RESP_DENOISING_210722]

2024-03-25 19:58 UTC, patriciampfigueiredo commented
Just read through the documentation, and I think it looks great! Congratulations on putting this together, I'm sure it will be a very valuable contribution to the community.

I left a few minor comments throughout, hope they are helpful!

2024-03-26 20:04 UTC, isesteves commented on docs/source/phys_set_up.md
> +You will require **peripheral devices**, typically attached to the subject, and **recording devices** (often connected to a computer/laptop) for data acquisition and storage. Post-recording, it is cr
Thanks Marie-Eve! I tried to reorder the sentence according to your suggestion (here 19f0024)

2024-03-26 20:46 UTC, isesteves commented on docs/source/collect_phys.md
> +ECG traces the potential change over the heart generated by the sinoatrial (SA) and atrioventricular (AV) nodes. It provides very precise beat-by-beat HR information. Depending on the system you are
Fixed here 6289ff6 to always use "heart rate".

2024-03-26 20:46 UTC, isesteves commented on docs/source/collect_phys.md
> +Inside the MRI environment, the ECG will be distorted by magnetic induction and RF pulses.
Fixed here 6289ff6 to always use "radiofrequency".

2024-03-26 20:46 UTC, isesteves commented on docs/source/collect_phys.md
> +It is important to note that like most signals, the ECG is susceptible to artifacts introduced by magnetic induction and RF pulses and to cardio-ballistic effects from the mechanical movement of the
Fixed here 6289ff6.

2024-03-26 20:47 UTC, isesteves commented on docs/source/collect_phys.md
Fixed here 6289ff6.

2024-03-27 15:16 UTC, isesteves commented on docs/source/phys_set_up.md
Regarding the Community Practices meetings references (e.g. [SETUP_170322]), we decided to remove them (kept them as a comment only, so they can still be tracked internally).

2024-03-27 16:09 UTC, isesteves commented
@m-miedema  https://github.com/physiopy/physiopy-community-guidelines/pull/3#issuecomment-1970991132

> It's exciting the way this is coming together! My main comments are that
> 
> 1. The in-text references to community meetings, while helpful internally, are not helpful in this context. Perhaps there could be a list of topics that have been discussed and in-text references that make it more clear that we're referencing a conversation? E.g. (Community Practice Meeting: Respiration, date).

We decided to remove them (kept them as a comment only, so they can still be tracked internally).

> 2. The comment regarding eddy currents should be moved out of the gas section and into a more general practice for collecting data.

This has been moved out from Data Collection collect_phys.md (here 6289ff6) to Setup phys_set_up.md (here 19f0024)

> 3. I'm not sure if this is in the scope of this PR, but section 6 seems to currently imply that e.g. HRV or other physiological derivatives should be directly input into a GLM. It seems unhelpful to include this section without at least mentioning PRFs.

This section has been removed for now until there are further updates (cd6a67b and c8d5b43)

Thanks Mary!

2024-03-27 16:34 UTC, isesteves commented on docs/source/physiopy_community.md
We changed this section to provide a brief introduction to the community and the Community Practices meetings, for some context. We are still including the types of signals, but now we introduce the acronyms (here ddcf641, d9a164e and the latest 6de1799)

2024-03-27 16:41 UTC, isesteves commented on docs/source/physio_importance.md
We have changed the text according to the comments and replaced the second appearance of the reference by Liu et al. (2019) and Pinto et al. (2021), since that sentence referred to mapping cerebrovascular reactivity (here ec1026b; the first reference was fixed here 6568c38).

2024-03-27 16:44 UTC, isesteves commented on docs/source/process_phys.md
Thank you! The typos were fixed and the Community Practices meetings in-text references ([RESP_DENOISING_210722]) were removed (they were kept only as a comment, to be tracked internally) (here 2119736).

2024-03-27 16:53 UTC, isesteves commented
@joanacspinto https://github.com/physiopy/physiopy-community-guidelines/pull/3#issuecomment-1991837247

> Hi all, I've taken a brief look at this - amazing work! Well done :) Just some minor points:
> 
> * the references to the community meetings look a bit odd

We agreed on this! We have decided to remove them and kept them as a comment only, so they can still be tracked internally.

> * the order. I would recommend moving "2. Community" to a later stage. I like the flow of 1. motivation, 2. setting up the system, 3. acquiring data, 3. analysing data etc

We have discussed this and the final decision was to move the Community section to the beginning and provide some more context about the Community Practices meetings to introduce the following sections (here ddcf641, d9a164e and the latest 6de1799).

Thank you Joana :)

2024-04-18 15:23 UTC, likeajumprope reviewed
Nice work! Some small changes within.

2024-04-18 15:23 UTC, likeajumprope commented on docs/source/phys_set_up.md
> +Some peripheral devices can be passed through a waveguide in the penetration panel from the control room to the scan room (e.g., gas sampling line); others must be plugged into the penetration panel
```suggestion
Some peripheral devices can be passed through a waveguide in the penetration panel from the control room to the scan room (e.g., gas sampling line); others must be plugged into the penetration panel for noise filtering (e.g., some pulse sensors). Devices native to the MRI scanner may communicate wirelessly with the scanner. When adding non-native peripheral devices to the scanner environment, we recommend that you check that you do not bring any outside noise into the scan room or bring too much scanner noise into the physiological recordings. It may be necessary to develop additional devices or mechanisms to shield these connections. Furthermore, looping of cords can create eddy currents that increase noise, so they should be taped down or placed on hooks to keep them in place. <!-- (SETUP_170322) -->
```

2024-05-13 17:22 UTC, isesteves commented
Hi all! Thank you again to all the reviewers who kindly went through the documentation so thoroughly 🙏 Before the final merge, could you please have a **final look at the revised version and confirm if you agree, until the end of this week (Friday, 19th of May)?** 
@smoia @beccaclements99 @goodalse2019 @RayStick @likeajumprope @rgbayrak @m-miedema @me-pic @joanacspinto @afni-dglen @patriciampfigueiredo 

Furthermore, if you have not done it yet, **please fill out this form** with your information: https://forms.gle/xdCpPt1frK3ZiZJC7

Thank you ☺️

2024-05-15 15:09 UTC, m-miedema commented
@isesteves what's the best way to confirm agreement? I know we have a limit on the number of official reviewers, so I wanted to clarify :)

2024-05-15 16:21 UTC, smoia commented
@m-miedema @isesteves if we agree, I'd suggest that either a :+1: to @isesteves 's message _or_ silence count as approval (as long as the authorship form has been filled in).
If you are listed as reviewer, it would be nice if you could make a second review and approve!

2024-05-15 17:53 UTC, m-miedema approved these changes

2024-05-21 12:26 UTC, RayStick approved these changes
Happy for it to be merged, looks great 👏

2024-05-27 06:35 UTC, smoia commented
@isesteves can I do something to help merging?

2024-05-28 20:40 UTC, smoia commented
Are we pushing the button?

Yes, we are.



:tada: :tada: :tada:

2024-05-28 20:40 UTC, merged

2024-05-28 20:40 UTC, smoia commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`2024.0.0`](https://github.com/physiopy/physiopy-community-guidelines/releases/tag/2024.0.0) :rocket: